[project]
name = "hands-on-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhoujiagen", email = "zhoujiagen@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "keras>=3.15.1",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.0",
    "tensorflow>=2.21.0",
]

[project.scripts]
hands-on-ml = "hands_on_ml:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
    "pandas-stubs>=3.0.5.260730",
    "pydot>=4.0.1",
    "pylint>=4.0.8",
    "tensorboard-plugin-profile>=2.23.1",
    "tensorflow-datasets>=4.9.10",
]
